"""audit log

Revision ID: c9439aab940d
Revises: deddda6d4642
Create Date: 2026-07-10 03:42:19.602643

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c9439aab940d"
down_revision: str | Sequence[str] | None = "deddda6d4642"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "actor",
            sa.Enum("human", "scheduler", "system", name="actor", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "created",
                "edited",
                "approved",
                "rejected",
                "reverted_to_draft",
                "scheduled",
                "published",
                "failed",
                "regenerated",
                name="audit_action",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "entity_type", sa.Enum("post", name="entity_type", native_enum=False), nullable=False
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_actor"), ["actor"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_type"), ["entity_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_actor"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
