"""content engine: posts, ai_calls, embeddings, voice_profile

Revision ID: deddda6d4642
Revises: c061c78df159
Create Date: 2026-07-10 03:13:07.158958

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "deddda6d4642"
down_revision: str | Sequence[str] | None = "c061c78df159"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_calls_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_calls_model"), ["model"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_calls_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_calls_purpose"), ["purpose"], unique=False)

    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("post", "job", "note", name="embedding_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_embeddings_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_embeddings_model_name"), ["model_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_embeddings_ref_id"), ["ref_id"], unique=False)

    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "scheduled",
                "published",
                "rejected",
                "failed",
                name="post_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("variant_group_id", sa.String(length=32), nullable=False),
        sa.Column("topic", sa.String(length=512), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linkedin_urn", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("linkedin_urn"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_posts_variant_group_id"), ["variant_group_id"], unique=False
        )

    op.create_table(
        "voice_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("examples", sa.Text(), nullable=False),
        sa.Column("guidelines", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_profile")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_variant_group_id"))
        batch_op.drop_index(batch_op.f("ix_posts_status"))

    op.drop_table("posts")
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_embeddings_ref_id"))
        batch_op.drop_index(batch_op.f("ix_embeddings_model_name"))
        batch_op.drop_index(batch_op.f("ix_embeddings_kind"))

    op.drop_table("embeddings")
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_calls_purpose"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_provider"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_model"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_at"))

    op.drop_table("ai_calls")
    # ### end Alembic commands ###
