"""add heartbeat table

Revision ID: c061c78df159
Revises: a60d11058e72
Create Date: 2026-07-10 02:46:17.885195

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c061c78df159"
down_revision: str | Sequence[str] | None = "a60d11058e72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heartbeat", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_heartbeat_beat_at"), ["beat_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heartbeat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_heartbeat_beat_at"))

    op.drop_table("heartbeat")
    # ### end Alembic commands ###
